### ISSUE TITLE
Should agree on a usable format for future consideration

### ISSUE THREAD

**Issue by yo1995** [chensunUofT/Reject_letter_generator#3]
We want to make this repo a usable corpora/library, either for NLP usage, e.g. rejection letter generator based on NN, or just as a reference for writing up a rejection letter for the industry.

Therefore, I suggest to make a formal template according to the standards on kaggle.com, and commit each textual file within such template.

Any ideas? @chensunUofT 🤔

**Comment by yo1995** [comment]
Out of my thought -  
industry,Company category, job title, location, subject, ,main body

**Comment by yo1995** [comment]
Use a YAML formatted *front matter* as a meta header, and append the main body with markdown syntax.

example as below:

```YAML
---
author: Ting
category: software engineering
title: mobile development engineer
company: ...
location: ...
subject: ...
---
```

- [ ]  will need to come up with a set of categories.
